/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import calculatorproject.Calculator;
import javax.swing.JTextField;
import calculatorproject.History;
/**
 *
 * @author BaoCôngIDOL
 */
public class KeyboardPanel extends javax.swing.JPanel {

    Calculator calculator;
    HistoryPanel history;
    JTextField screen;
    /**
     * Creates new form Keyboard
     */
    public void setHistory(HistoryPanel h){
        history=h;
    }
    public void setCalculator(Calculator c){
        calculator=c;
    }
    public void setScreen(JTextField s){
        screen=s;
    }
    public KeyboardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        num2Btn = new javax.swing.JButton();
        num7Btn = new javax.swing.JButton();
        num1Btn = new javax.swing.JButton();
        num5Btn = new javax.swing.JButton();
        num3Btn = new javax.swing.JButton();
        num6Btn = new javax.swing.JButton();
        num8Btn = new javax.swing.JButton();
        equalBtn = new javax.swing.JButton();
        num9Btn = new javax.swing.JButton();
        subBtn = new javax.swing.JButton();
        plusBtn = new javax.swing.JButton();
        num0Btn = new javax.swing.JButton();
        num4Btn = new javax.swing.JButton();

        jButton10.setText("jButton1");

        jButton12.setText("jButton1");

        num2Btn.setText("2");
        num2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2BtnActionPerformed(evt);
            }
        });

        num7Btn.setText("7");
        num7Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7BtnActionPerformed(evt);
            }
        });

        num1Btn.setText("1");
        num1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1BtnActionPerformed(evt);
            }
        });

        num5Btn.setText("5");
        num5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5BtnActionPerformed(evt);
            }
        });

        num3Btn.setText("3");
        num3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3BtnActionPerformed(evt);
            }
        });

        num6Btn.setText("6");
        num6Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6BtnActionPerformed(evt);
            }
        });

        num8Btn.setText("8");
        num8Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8BtnActionPerformed(evt);
            }
        });

        equalBtn.setText("=");
        equalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalBtnActionPerformed(evt);
            }
        });

        num9Btn.setText("9");
        num9Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9BtnActionPerformed(evt);
            }
        });

        subBtn.setText("-");
        subBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnActionPerformed(evt);
            }
        });

        plusBtn.setText("+");
        plusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusBtnActionPerformed(evt);
            }
        });

        num0Btn.setText("0");
        num0Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0BtnActionPerformed(evt);
            }
        });

        num4Btn.setText("4");
        num4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(num1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(plusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(num4Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num5Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num6Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(num7Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(num0Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(num8Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(num9Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(num5Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(num6Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(num4Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num7Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num8Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num9Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(num0Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void subBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnActionPerformed
        // TODO add your handling code here:
        calculator.addElement(subBtn.getText());
        screen.setText(calculator.inScreen());
    }//GEN-LAST:event_subBtnActionPerformed

    private void num5BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5BtnActionPerformed
        // TODO add your handling code here:
        calculator.addElement(num1Btn.getText());
        screen.setText(calculator.inScreen());
    }//GEN-LAST:event_num5BtnActionPerformed

    private void num4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4BtnActionPerformed
        // TODO add your handling code here:
        calculator.addElement(num4Btn.getText());
        screen.setText(calculator.inScreen());
    }//GEN-LAST:event_num4BtnActionPerformed

    private void num1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1BtnActionPerformed
        // TODO add your handling code here:
        calculator.addElement(num1Btn.getText());
        screen.setText(calculator.inScreen());
    }//GEN-LAST:event_num1BtnActionPerformed

    private void num2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2BtnActionPerformed
        // TODO add your handling code here:
        calculator.addElement(num2Btn.getText());
        screen.setText(calculator.inScreen());
    }//GEN-LAST:event_num2BtnActionPerformed

    private void num3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3BtnActionPerformed
        // TODO add your handling code here:
        calculator.addElement(num3Btn.getText());
        screen.setText(calculator.inScreen());
    }//GEN-LAST:event_num3BtnActionPerformed

    private void num6BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6BtnActionPerformed
        // TODO add your handling code here:
        calculator.addElement(num6Btn.getText());
        screen.setText(calculator.inScreen());
    }//GEN-LAST:event_num6BtnActionPerformed

    private void num7BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7BtnActionPerformed
        // TODO add your handling code here:
        calculator.addElement(num7Btn.getText());
        screen.setText(calculator.inScreen());
    }//GEN-LAST:event_num7BtnActionPerformed

    private void num8BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8BtnActionPerformed
        // TODO add your handling code here:
        calculator.addElement(num8Btn.getText());
        screen.setText(calculator.inScreen());
    }//GEN-LAST:event_num8BtnActionPerformed

    private void num9BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9BtnActionPerformed
        // TODO add your handling code here:
        calculator.addElement(num9Btn.getText());
        screen.setText(calculator.inScreen());
    }//GEN-LAST:event_num9BtnActionPerformed

    private void num0BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0BtnActionPerformed
        // TODO add your handling code here:
        calculator.addElement(num0Btn.getText());
        screen.setText(calculator.inScreen());
    }//GEN-LAST:event_num0BtnActionPerformed

    private void plusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusBtnActionPerformed
        // TODO add your handling code here:
        calculator.addElement(plusBtn.getText());
        screen.setText(calculator.inScreen());
    }//GEN-LAST:event_plusBtnActionPerformed

    private void equalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalBtnActionPerformed
        // TODO add your handling code here:
        String s=calculator.calculate();
        if(!s.contains("=")) return;
        history.addToHistory(s);
        screen.setText(s);
    }//GEN-LAST:event_equalBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton equalBtn;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton num0Btn;
    private javax.swing.JButton num1Btn;
    private javax.swing.JButton num2Btn;
    private javax.swing.JButton num3Btn;
    private javax.swing.JButton num4Btn;
    private javax.swing.JButton num5Btn;
    private javax.swing.JButton num6Btn;
    private javax.swing.JButton num7Btn;
    private javax.swing.JButton num8Btn;
    private javax.swing.JButton num9Btn;
    private javax.swing.JButton plusBtn;
    private javax.swing.JButton subBtn;
    // End of variables declaration//GEN-END:variables
}
